import Head from 'next/head'
import { useSelector } from 'react-redux'
import { QuoteTabs, QuoteForm, Menu } from '../widgets';

export default function Home() {
  const quote = useSelector(s => s.quote);
  return (
    <div className="home">
      <Head>
        <title>Member Quote Comparison</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> 
      
      <h6><Menu />Member Quote Comparison </h6>
      
      {quote.list.length > 0 && <QuoteTabs />}

      {quote.list.length > 0 && <QuoteForm />}

      <style jsx>{`
        .home {
          width: 100%;
          display: flex;
          flex-flow: column wrap;
          align-items: center;
          justify-content: space-between;
        }

        h6 {
          display: flex;
          padding: 2rem;
          gap: 2rem;
        }      

        .vzw {
          background-color: var(--vzw-red);
        }

        .att {
          background-color: var(--att-blue);
        }

        .tmo {
          background-color: var(--tmo-magenta);
        }
        
      `}</style>
    </div>
  )
}
