import Head from 'next/head'
import { useSelector } from 'react-redux'
import { QuoteTabs, QuoteForm, Navbar } from '../widgets';

export default function Home() {
  const quote = useSelector(s => s.quote);
  return (
    <div className="home">
      <Head>
        <title>Member Quote Comparison</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> 
      
      <Navbar/>
      
      {quote.list.length > 0 && <QuoteTabs />}

      {quote.list.length > 0 && <QuoteForm />}

      <style jsx>{`
        .home {
          width: 100%;
          display: flex;
          flex-flow: column wrap;
          align-items: center;
          justify-content: space-between;
        }
      `}</style>
    </div>
  )
}
